// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OeeApi.Migrations
{
    [DbContext(typeof(OeeDbContext))]
    [Migration("20260706033554_AddAllTables")]
    partial class AddAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MachineEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualRate")
                        .HasColumnType("integer");

                    b.Property<int>("GoodUnits")
                        .HasColumnType("integer");

                    b.Property<int>("IdealRate")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlannedTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("RunTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("UnitsProduced")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("OeeReadingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActualRate")
                        .HasColumnType("integer");

                    b.Property<decimal>("Availability")
                        .HasColumnType("numeric");

                    b.Property<int>("GoodUnits")
                        .HasColumnType("integer");

                    b.Property<int>("IdealRate")
                        .HasColumnType("integer");

                    b.Property<int>("MachineId")
                        .HasColumnType("integer");

                    b.Property<decimal>("OeeScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Performance")
                        .HasColumnType("numeric");

                    b.Property<int>("PlannedTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quality")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RunTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OeeReadings");
                });

            modelBuilder.Entity("UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VerificationCodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VerificationCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
